// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmh5r3FHpY_eLQZLVqVDalXsmNkbtxHkk',
    appId: '1:751115509036:web:68fa7eb9952a7c22412089',
    messagingSenderId: '751115509036',
    projectId: 'myfirebaseapp-d86ae',
    authDomain: 'myfirebaseapp-d86ae.firebaseapp.com',
    storageBucket: 'myfirebaseapp-d86ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7WROBdryyDXq5s6_A3uI4FoLypa116f0',
    appId: '1:751115509036:android:6a4c43bc4c703d85412089',
    messagingSenderId: '751115509036',
    projectId: 'myfirebaseapp-d86ae',
    storageBucket: 'myfirebaseapp-d86ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXL9zzZSyeQml6ToovDu-EdjUs8Jyg8lo',
    appId: '1:751115509036:ios:9c8e8d639df9bad6412089',
    messagingSenderId: '751115509036',
    projectId: 'myfirebaseapp-d86ae',
    storageBucket: 'myfirebaseapp-d86ae.firebasestorage.app',
    iosClientId: '751115509036-94la5dhbjt13rar1ja9c010sjel7ut6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXL9zzZSyeQml6ToovDu-EdjUs8Jyg8lo',
    appId: '1:751115509036:ios:9c8e8d639df9bad6412089',
    messagingSenderId: '751115509036',
    projectId: 'myfirebaseapp-d86ae',
    storageBucket: 'myfirebaseapp-d86ae.firebasestorage.app',
    iosClientId: '751115509036-94la5dhbjt13rar1ja9c010sjel7ut6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmh5r3FHpY_eLQZLVqVDalXsmNkbtxHkk',
    appId: '1:751115509036:web:b55a305e659ae673412089',
    messagingSenderId: '751115509036',
    projectId: 'myfirebaseapp-d86ae',
    authDomain: 'myfirebaseapp-d86ae.firebaseapp.com',
    storageBucket: 'myfirebaseapp-d86ae.firebasestorage.app',
  );

}